services:
    smac-front:
        build: .
        container_name: smac-front_c
        env_file:
            - .env
        ports:
            - '5173:5173'
        volumes:
            - .:/app
            - /app/node_modules
